######################################################################
##
## Filename: alu_tb.udo
## Created on: Tue Oct 08 03:59:28 Romance Daylight Time 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
