######################################################################
##
## Filename: ALU_control.udo
## Created on: Sat Oct 05 19:10:35 Romance Daylight Time 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
