######################################################################
##
## Filename: proc_control_module_tb.udo
## Created on: Sun Sep 29 13:34:18 Romance Daylight Time 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
